title: AI Conference Deadlines # (Forked from @abhshkdz)
description: Countdowns to top NLP/ML/KG/AI conference deadlines. Focus on conferences related to the use of graph machine learning and NLP in drug discovery.


twitter_username: elipapa
twitter_hashtag: machinelearning

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
plugins:
  - "jekyll-github-metadata"